name: Continuous-Integration

on: [push, pull_request]

jobs:
  Continuous-Integration:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v3

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install packages
        run: poetry install

      - name: Run tests
        run: poetry run pytest tests/ --cov=pycounts --cov-report=xml

      - name: Track test coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml   # coverage report

      - name: Build docs
        run: poetry run make html --directory docs/